/**
 * key.h
 * Keyboard Translation Tables
 */

#include "../plato_key.h"

#ifndef KEY_H
#define KEY_H

/**
 *
 * KEY_H generated by mk_ascii_key_h.c
 */


unsigned char key_to_pkey[]={
    PKEY_NOKEY,     /* 0x00 NONE */
    PKEY_ANS,       /* 0x01 CTRL-A */
    PKEY_BACK,      /* 0x02 CTRL-B */
    PKEY_COPY,      /* 0x03 CTRL-C */
    PKEY_DATA,      /* 0x04 CTRL-D */
    PKEY_EDIT,      /* 0x05 CTRL-E */
    PKEY_FONT,      /* 0x06 CTRL-F */
    PKEY_DIVIDE,    /* 0x07 CTRL-G */
    PKEY_HELP,      /* 0x08 CTRL-H */
    PKEY_NOKEY,    /* 0x09 0x0a 0x0b CTRL-H, I, J */
    PKEY_NOKEY,    /* 0x09 0x0a 0x0b CTRL-H, I, J */
    PKEY_NOKEY,    /* 0x09 0x0a 0x0b CTRL-H, I, J */
    PKEY_LAB,      /* 0x0c CTRL-L */
    PKEY_NEXT,     /* 0x0d CTRL-M */
    PKEY_NOKEY,    /* 0x0e 0x0f CTRL-N, O */
    PKEY_NOKEY,    /* 0x0e 0x0f CTRL-N, O */
    PKEY_SUPER,    /* 0x10 CTRL-P */
    PKEY_SQUARE,   /* 0x11 CTRL-Q */
    PKEY_ERASE,    /* 0x12 CTRL-R */
    PKEY_STOP,     /* 0x13 CTRL-S */
    PKEY_TERM,     /* 0x14 CTRL-T */
    PKEY_NOKEY,    /* 0x15 0x16 0x17 CTRL U, V, W */
    PKEY_NOKEY,    /* 0x15 0x16 0x17 CTRL U, V, W */
    PKEY_NOKEY,    /* 0x15 0x16 0x17 CTRL U, V, W */
    PKEY_MULTIPLY, /* 0x18 CTRL-X */
    PKEY_SUB,      /* 0x19 CTRL-Y */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_SUB,      /* 0x19 CTRL-Y */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */
    PKEY_SPACE,    /* 0x20 SPACE */
    PKEY_EXCLAMATION, /* 0x21 ! */
    PKEY_QUOTE,    /* 0x22 " */
    PKEY_POUND,    /* 0x23 # */
    PKEY_DOLLAR,   /* 0x24 $ */
    PKEY_PERCENT,  /* 0x25 PERCENT */
    PKEY_AMPERSAND, /* 0x26 & */
    PKEY_APOSTROPHE, /* 0x27 ' */    PKEY_PARENTHESIS_LEFT, /* 0x28 ( */
    PKEY_PARENTHESIS_RIGHT, /* 0x29 ) */
    PKEY_ASTERISK,         /* 0x2A * */
    PKEY_PLUS,             /* 0x2B + */
    PKEY_COMMA,            /* 0x2C , */
    PKEY_MINUS,            /* 0x2D - */
    PKEY_PERIOD,           /* 0x2E . */
    PKEY_SLASH,           /* 0x2F / */
    PKEY_0,       /* 0x30   */
    PKEY_1,       /* 0x31   */
    PKEY_2,       /* 0x32   */
    PKEY_3,       /* 0x33   */
    PKEY_4,       /* 0x34   */
    PKEY_5,       /* 0x35   */
    PKEY_6,       /* 0x36   */
    PKEY_7,       /* 0x37   */
    PKEY_8,       /* 0x38   */
    PKEY_9,       /* 0x39   */
    PKEY_COLON,          /* 0x3A : */
    PKEY_SEMICOLON,      /* 0x3B ; */
    PKEY_LESS_THAN,      /* 0x3C < */
    PKEY_EQUALS,         /* 0x3D = */
    PKEY_GREATER_THAN,   /* 0x3E > */
    PKEY_QUESTION_MARK,  /* 0x3F ? */
    PKEY_AT,             /* 0x40 @ */
    PKEY_A,       /* 0x41   */
    PKEY_B,       /* 0x42   */
    PKEY_C,       /* 0x43   */
    PKEY_D,       /* 0x44   */
    PKEY_E,       /* 0x45   */
    PKEY_F,       /* 0x46   */
    PKEY_G,       /* 0x47   */
    PKEY_H,       /* 0x48   */
    PKEY_I,       /* 0x49   */
    PKEY_J,       /* 0x4a   */
    PKEY_K,       /* 0x4b   */
    PKEY_L,       /* 0x4c   */
    PKEY_M,       /* 0x4d   */
    PKEY_N,       /* 0x4e   */
    PKEY_O,       /* 0x4f   */
    PKEY_P,       /* 0x50   */
    PKEY_Q,       /* 0x51   */
    PKEY_R,       /* 0x52   */
    PKEY_S,       /* 0x53   */
    PKEY_T,       /* 0x54   */
    PKEY_U,       /* 0x55   */
    PKEY_V,       /* 0x56   */
    PKEY_W,       /* 0x57   */
    PKEY_X,       /* 0x58   */
    PKEY_Y,       /* 0x59   */
    PKEY_Z,       /* 0x5a   */
    PKEY_BRACKET_LEFT,   /* 0x5B [ */
    PKEY_BACKSLASH,      /* 0x5C \ */
    PKEY_BRACKET_RIGHT,  /* 0x5D ] */
    PKEY_CIRCUMFLEX,     /* 0x5E ^ */
    PKEY_UNDERSCORE,     /* 0x5F _ */
    PKEY_GRAVE,          /* 0x60 ` */
    PKEY_a,       /* 0x61   */
    PKEY_b,       /* 0x62   */
    PKEY_c,       /* 0x63   */
    PKEY_d,       /* 0x64   */
    PKEY_e,       /* 0x65   */
    PKEY_f,       /* 0x66   */
    PKEY_g,       /* 0x67   */
    PKEY_h,       /* 0x68   */
    PKEY_i,       /* 0x69   */
    PKEY_j,       /* 0x6a   */
    PKEY_k,       /* 0x6b   */
    PKEY_l,       /* 0x6c   */
    PKEY_m,       /* 0x6d   */
    PKEY_n,       /* 0x6e   */
    PKEY_o,       /* 0x6f   */
    PKEY_p,       /* 0x70   */
    PKEY_q,       /* 0x71   */
    PKEY_r,       /* 0x72   */
    PKEY_s,       /* 0x73   */
    PKEY_t,       /* 0x74   */
    PKEY_u,       /* 0x75   */
    PKEY_v,       /* 0x76   */
    PKEY_w,       /* 0x77   */
    PKEY_x,       /* 0x78   */
    PKEY_y,       /* 0x79   */
    PKEY_z,       /* 0x7a   */
    PKEY_LEFT_CURLY_BRACE, /* 0x7B { */
    PKEY_BAR,             /* 0x7C | */
    PKEY_RIGHT_CURLY_BRACE, /* 0x7D } */
    PKEY_TILDE,             /* 0x7E ~ */
    PKEY_ERASE,             /* 0x7F DEL */
};

unsigned char esc_key_to_pkey[]={
    PKEY_NOKEY,       /* 0x00 Not Used */
    PKEY_TERM,     /* 0x01 ESC CTRL-A */
    PKEY_BACK1,    /* 0x02 ESC CTRL-B */
    PKEY_COPY1,    /* 0x03 ESC CTRL-C */
    PKEY_DATA1,    /* 0x04 ESC CTRL-D */
    PKEY_EDIT1,   /* 0x05 ESC CTRL-E */
    PKEY_FONT,    /* 0x06 ESC CTRL-F */
    PKEY_NOKEY,       /* 0x07 Not Used */
    PKEY_HELP1,   /* 0x08 ESC CTRL-H */
    PKEY_NOKEY,       /* 0x09 Not Used */
    PKEY_NOKEY,       /* 0x0a Not Used */
    PKEY_NOKEY,       /* 0x0b Not Used */
    PKEY_LAB1,    /* 0x0C ESC CTRL-L */
    PKEY_NEXT1,   /* 0x0D ESC RETURN */
    PKEY_NOKEY,       /* 0x0e Not Used */
    PKEY_NOKEY,       /* 0x0f Not Used */
    PKEY_SUPER1,  /* 0x10 ESC CTRL-P */
    PKEY_ACCESS,  /* 0x11 ESC CTRL-Q */
    PKEY_ERASE1,  /* 0x12 ESC CTRL-R */
    PKEY_STOP1,   /* 0x13 ESC CTRL-S */
    PKEY_NOKEY,       /* 0x14 Not Used */
    PKEY_NOKEY,       /* 0x15 Not Used */
    PKEY_NOKEY,       /* 0x16 Not Used */
    PKEY_NOKEY,       /* 0x17 Not Used */
    PKEY_NOKEY,       /* 0x18 Not Used */
    PKEY_SUB1,   /* 0x19 ESC CTRL-Y */
    PKEY_NOKEY,       /* 0x1a Not Used */
    PKEY_NOKEY,       /* 0x1b Not Used */
    PKEY_NOKEY,       /* 0x1c Not Used */
    PKEY_NOKEY,       /* 0x1d Not Used */
    PKEY_NOKEY,       /* 0x1e Not Used */
    PKEY_NOKEY,       /* 0x1f Not Used */
    PKEY_NOKEY,       /* 0x20 Not Used */
    PKEY_NOKEY,       /* 0x21 Not Used */
    PKEY_NOKEY,       /* 0x22 Not Used */
    PKEY_NOKEY,       /* 0x23 Not Used */
    PKEY_NOKEY,       /* 0x24 Not Used */
    PKEY_NOKEY,       /* 0x25 Not Used */
    PKEY_NOKEY,       /* 0x26 Not Used */
    PKEY_NOKEY,       /* 0x27 Not Used */
    PKEY_NOKEY,       /* 0x28 Not Used */
    PKEY_NOKEY,       /* 0x29 Not Used */
    PKEY_NOKEY,       /* 0x2a Not Used */
    PKEY_NOKEY,       /* 0x2b Not Used */
    PKEY_NOKEY,       /* 0x2c Not Used */
    PKEY_NOKEY,       /* 0x2d Not Used */
    PKEY_NOKEY,       /* 0x2e Not Used */
    PKEY_NOKEY,       /* 0x2f Not Used */
    PKEY_NOKEY,       /* 0x30 Not Used */
    PKEY_NOKEY,       /* 0x31 Not Used */
    PKEY_NOKEY,       /* 0x32 Not Used */
    PKEY_NOKEY,       /* 0x33 Not Used */
    PKEY_NOKEY,       /* 0x34 Not Used */
    PKEY_NOKEY,       /* 0x35 Not Used */
    PKEY_NOKEY,       /* 0x36 Not Used */
    PKEY_NOKEY,       /* 0x37 Not Used */
    PKEY_NOKEY,       /* 0x38 Not Used */
    PKEY_NOKEY,       /* 0x39 Not Used */
    PKEY_NOKEY,       /* 0x3a Not Used */
    PKEY_NOKEY,       /* 0x3b Not Used */
    PKEY_NOKEY,       /* 0x3c Not Used */
    PKEY_NOKEY,       /* 0x3d Not Used */
    PKEY_NOKEY,       /* 0x3e Not Used */
    PKEY_NOKEY,       /* 0x3f Not Used */
    PKEY_NOKEY,       /* 0x40 Not Used */
    PKEY_NOKEY,       /* 0x41 Not Used */
    PKEY_NOKEY,       /* 0x42 Not Used */
    PKEY_NOKEY,       /* 0x43 Not Used */
    PKEY_NOKEY,       /* 0x44 Not Used */
    PKEY_NOKEY,       /* 0x45 Not Used */
    PKEY_NOKEY,       /* 0x46 Not Used */
    PKEY_NOKEY,       /* 0x47 Not Used */
    PKEY_NOKEY,       /* 0x48 Not Used */
    PKEY_NOKEY,       /* 0x49 Not Used */
    PKEY_NOKEY,       /* 0x4a Not Used */
    PKEY_NOKEY,       /* 0x4b Not Used */
    PKEY_NOKEY,       /* 0x4c Not Used */
    PKEY_NOKEY,       /* 0x4d Not Used */
    PKEY_NOKEY,       /* 0x4e Not Used */
    PKEY_NOKEY,       /* 0x4f Not Used */
    PKEY_NOKEY,       /* 0x50 Not Used */
    PKEY_NOKEY,       /* 0x51 Not Used */
    PKEY_NOKEY,       /* 0x52 Not Used */
    PKEY_NOKEY,       /* 0x53 Not Used */
    PKEY_NOKEY,       /* 0x54 Not Used */
    PKEY_NOKEY,       /* 0x55 Not Used */
    PKEY_NOKEY,       /* 0x56 Not Used */
    PKEY_NOKEY,       /* 0x57 Not Used */
    PKEY_NOKEY,       /* 0x58 Not Used */
    PKEY_NOKEY,       /* 0x59 Not Used */
    PKEY_NOKEY,       /* 0x5a Not Used */
    PKEY_NOKEY,       /* 0x5b Not Used */
    PKEY_NOKEY,       /* 0x5c Not Used */
    PKEY_NOKEY,       /* 0x5d Not Used */
    PKEY_NOKEY,       /* 0x5e Not Used */
    PKEY_NOKEY,       /* 0x5f Not Used */
    PKEY_NOKEY,       /* 0x60 Not Used */
    PKEY_NOKEY,       /* 0x61 Not Used */
    PKEY_NOKEY,       /* 0x62 Not Used */
    PKEY_NOKEY,       /* 0x63 Not Used */
    PKEY_NOKEY,       /* 0x64 Not Used */
    PKEY_NOKEY,       /* 0x65 Not Used */
    PKEY_NOKEY,       /* 0x66 Not Used */
    PKEY_NOKEY,       /* 0x67 Not Used */
    PKEY_NOKEY,       /* 0x68 Not Used */
    PKEY_NOKEY,       /* 0x69 Not Used */
    PKEY_NOKEY,       /* 0x6a Not Used */
    PKEY_NOKEY,       /* 0x6b Not Used */
    PKEY_NOKEY,       /* 0x6c Not Used */
    PKEY_NOKEY,       /* 0x6d Not Used */
    PKEY_NOKEY,       /* 0x6e Not Used */
    PKEY_NOKEY,       /* 0x6f Not Used */
    PKEY_NOKEY,       /* 0x70 Not Used */
    PKEY_NOKEY,       /* 0x71 Not Used */
    PKEY_NOKEY,       /* 0x72 Not Used */
    PKEY_NOKEY,       /* 0x73 Not Used */
    PKEY_NOKEY,       /* 0x74 Not Used */
    PKEY_NOKEY,       /* 0x75 Not Used */
    PKEY_NOKEY,       /* 0x76 Not Used */
    PKEY_NOKEY,       /* 0x77 Not Used */
    PKEY_NOKEY,       /* 0x78 Not Used */
    PKEY_NOKEY,       /* 0x79 Not Used */
    PKEY_NOKEY,       /* 0x7a Not Used */
    PKEY_NOKEY,       /* 0x7b Not Used */
    PKEY_NOKEY,       /* 0x7c Not Used */
    PKEY_NOKEY,       /* 0x7d Not Used */
    PKEY_NOKEY,       /* 0x7e Not Used */
    PKEY_NOKEY,       /* 0x7f Not Used */
};

#endif /* KEY_H */
