/**
 * Tool to create initial key map for ASCII keyboards (apple II)
 * 
 * Author: Thomas Cherryhomes <thom.cherryhomes@gmail.com>
 *
 */

#include <stdio.h>
#include <stdlib.h>

void main(void)
{
  unsigned int i=0;
  printf("/**\n");
  printf(" *\n");
  printf(" * KEY_H generated by mk_ascii_key_h.c\n");
  printf(" */\n");
  printf("\n\n");

  printf("unsigned char key_to_pkey[]={\n");

  for (i=0;i<128;++i)
    {
      switch(i)
	{
	case 0x00:
	  printf("    PKEY_NOKEY,     /* 0x00 NONE */\n");
	  break;
	case 0x01:
	  printf("    PKEY_ANS,       /* 0x01 CTRL-A */\n");
	  break;
	case 0x02:
	  printf("    PKEY_BACK,      /* 0x02 CTRL-B */\n");
	  break;
	case 0x03:
	  printf("    PKEY_COPY,      /* 0x03 CTRL-C */\n");
	  break;
	case 0x04:
	  printf("    PKEY_DATA,      /* 0x04 CTRL-D */\n");
	  break;
	case 0x05:
	  printf("    PKEY_EDIT,      /* 0x05 CTRL-E */\n");
	  break;
	case 0x06:
	  printf("    PKEY_FONT,      /* 0x06 CTRL-F */\n");
	  break;
	case 0x07:
	  printf("    PKEY_DIVIDE,    /* 0x07 CTRL-G */\n");
	  break;
	case 0x08:
	  printf("    PKEY_HELP,      /* 0x08 CTRL-H */\n");
	  break;
	case 0x09:
	case 0x0A:
	case 0x0B:
	  printf("    PKEY_NOKEY,    /* 0x09 0x0a 0x0b CTRL-H, I, J */\n");
	  break;
	case 0x0C:
	  printf("    PKEY_LAB,      /* 0x0c CTRL-L */\n");
	  break;
	case 0x0D:
	  printf("    PKEY_NEXT,     /* 0x0d CTRL-M */\n");
	  break;
	case 0x0E:
	case 0x0F:
	  printf("    PKEY_NOKEY,    /* 0x0e 0x0f CTRL-N, O */\n");
	  break;
	case 0x10:
	  printf("    PKEY_SUPER,    /* 0x10 CTRL-P */\n");
	  break;
	case 0x11:
	  printf("    PKEY_SQUARE,   /* 0x11 CTRL-Q */\n");
	  break;
	case 0x12:
	  printf("    PKEY_ERASE,    /* 0x12 CTRL-R */\n");
	  break;
	case 0x13:
	  printf("    PKEY_STOP,     /* 0x13 CTRL-S */\n");
	  break;
	case 0x14:
	  printf("    PKEY_TERM,     /* 0x14 CTRL-T */\n");
	  break;
	case 0x15:
	case 0x16:
	case 0x17:
	  printf("    PKEY_NOKEY,    /* 0x15 0x16 0x17 CTRL U, V, W */\n");
	  break;
	case 0x18:
	  printf("    PKEY_MULTIPLY, /* 0x18 CTRL-X */\n");
	case 0x19:
	  printf("    PKEY_SUB,      /* 0x19 CTRL-Y */\n");
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	  printf("    PKEY_NOKEY,    /* 0x1A, 1B, 1C, 1D, 1E, 1F No keys for rest of ctrl chars. */\n");
	  break;
	case 0x20:
	  printf("    PKEY_SPACE,    /* 0x20 SPACE */\n");
	  break;
	case 0x21:
	  printf("    PKEY_EXCLAMATION, /* 0x21 ! */\n");
	  break;
	case 0x22:
	  printf("    PKEY_QUOTE,    /* 0x22 \" */\n");
	  break;
	case 0x23:
	  printf("    PKEY_POUND,    /* 0x23 # */\n");
	  break;
	case 0x24:
	  printf("    PKEY_DOLLAR,   /* 0x24 $ */\n");
	  break;
	case 0x25:
	  printf("    PKEY_PERCENT,  /* 0x25 PERCENT */\n");
	  break;
	case 0x26:
	  printf("    PKEY_AMPERSAND, /* 0x26 & */\n");
	  break;
	case 0x27:
	  printf("    PKEY_APOSTROPHE, /* 0x27 ' */");
	  break;
	case 0x28:
	  printf("    PKEY_PARENTHESIS_LEFT, /* 0x28 ( */\n");
	  break;
	case 0x29:
	  printf("    PKEY_PARENTHESIS_RIGHT, /* 0x29 ) */\n");
	  break;
	case 0x2A:
	  printf("    PKEY_ASTERISK,         /* 0x2A * */\n");
	  break;
	case 0x2B:
	  printf("    PKEY_PLUS,             /* 0x2B + */\n");
	  break;
	case 0x2C:
	  printf("    PKEY_COMMA,            /* 0x2C , */\n");
	  break;
	case 0x2D:
	  printf("    PKEY_MINUS,            /* 0x2D - */\n");
	  break;
	case 0x2E:
	  printf("    PKEY_PERIOD,           /* 0x2E . */\n");
	  break;
	case 0x2F:
	  printf("    PKEY_SLASH,           /* 0x2F / */\n");
	  break;
	case 0x3A:
	  printf("    PKEY_COLON,          /* 0x3A : */\n");
	  break;
	case 0x3B:
	  printf("    PKEY_SEMICOLON,      /* 0x3B ; */\n");
	  break;
	case 0x3C:
	  printf("    PKEY_LESS_THAN,      /* 0x3C < */\n");
	  break;
	case 0x3D:
	  printf("    PKEY_EQUALS,         /* 0x3D = */\n");
	  break;
	case 0x3E:
	  printf("    PKEY_GREATER_THAN,   /* 0x3E > */\n");
	  break;
	case 0x3F:
	  printf("    PKEY_QUESTION_MARK,  /* 0x3F ? */\n");
	  break;
	case 0x40:
	  printf("    PKEY_AT,             /* 0x40 @ */\n");
	  break;
	case 0x5B:
	  printf("    PKEY_BRACKET_LEFT,   /* 0x5B [ */\n");
	  break;
	case 0x5C:
	  printf("    PKEY_BACKSLASH,      /* 0x5C \\ */\n");
	  break;
	case 0x5D:
	  printf("    PKEY_BRACKET_RIGHT,  /* 0x5D ] */\n");
	  break;
	case 0x5E:
	  printf("    PKEY_CIRCUMFLEX,     /* 0x5E ^ */\n");
	  break;
	case 0x5F:
	  printf("    PKEY_UNDERSCORE,     /* 0x5F _ */\n");
	  break;
	case 0x60:
	  printf("    PKEY_GRAVE,          /* 0x60 ` */\n");
	  break;
	case 0x7B:
	  printf("    PKEY_LEFT_CURLY_BRACE, /* 0x7B { */\n");
	  break;
	case 0x7C:
	  printf("    PKEY_BAR,             /* 0x7C | */\n");
	  break;
	case 0x7D:
	  printf("    PKEY_RIGHT_CURLY_BRACE, /* 0x7D } */\n");
	  break;
	case 0x7E:
	  printf("    PKEY_TILDE,             /* 0x7E ~ */\n");
	  break;
	case 0x7F:
	  printf("    PKEY_ERASE,             /* 0x7F DEL */\n");
	  break;
	default:
	  printf("    PKEY_%c,       /* 0x%02x %c */\n",i,i);
	  break;
	}
    }

  printf("};\n\n");

  printf("unsigned char esc_key_to_pkey[]={\n");

  for (i=0;i<128;++i)
    {
      switch(i)
	{
	case 0x01:
	  printf("    PKEY_TERM,     /* 0x01 ESC CTRL-A */\n");
	  break;
	case 0x02:
	  printf("    PKEY_BACK1,    /* 0x02 ESC CTRL-B */\n");
	  break;
	case 0x03:
	  printf("    PKEY_COPY1,    /* 0x03 ESC CTRL-C */\n");
	  break;
	case 0x04:
	  printf("    PKEY_DATA1,    /* 0x04 ESC CTRL-D */\n");
	  break;
	case 0x05:
	  printf("    PKEY_EDIT1,   /* 0x05 ESC CTRL-E */\n");
	  break;
	case 0x06:
	  printf("    PKEY_FONT,    /* 0x06 ESC CTRL-F */\n");
	  break;
	case 0x08:
	  printf("    PKEY_HELP1,   /* 0x08 ESC CTRL-H */\n");
	  break;
	case 0x0C:
	  printf("    PKEY_LAB1,    /* 0x0C ESC CTRL-L */\n");
	  break;
	case 0x0D:
	  printf("    PKEY_NEXT1,   /* 0x0D ESC RETURN */\n");
	  break;
	case 0x10:
	  printf("    PKEY_SUPER1,  /* 0x10 ESC CTRL-P */\n");
	  break;
	case 0x11:
	  printf("    PKEY_ACCESS,  /* 0x11 ESC CTRL-Q */\n");
	  break;
	case 0x12:
	  printf("    PKEY_ERASE1,  /* 0x12 ESC CTRL-R */\n");
	  break;
	case 0x13:
	  printf("    PKEY_STOP1,   /* 0x13 ESC CTRL-S */\n");
	  break;
	case 0x19:
	  printf("    PKEY_SUB1,   /* 0x19 ESC CTRL-Y */\n");
	  break;
	default:
	  printf("    PKEY_NOKEY,       /* 0x%02x Not Used */\n",i);
	  break;
	}
    }

  
  printf("};\n");
  
}
